### ISSUE TITLE
Fork of python-docx?

### ISSUE THREAD

**Issue by buhtz** [jaraco/paradocx#1]
Hi Jaraco,

just for my own research.

Is your `paradocx` a fork of `python-docx`?

**Comment by jaraco** [comment]
It is not. It was once at dowski/paradocx and then yougov/paradocx. This project was started in 2008 and presented at PyCon in 2011. python-docx was started in Aug 2013. Shame that project didn't contribute to this one instead.

**Comment by buhtz** [comment]
Thanks for explaining this.

IMHO this information should be written into the README.md. This would help potential contributors to better "locate" your project in the FOSS universe.

One difference I noticed between your project and python-docx is the documentation. Paradocx don't have a API documentation. That was one of the reasons why I decided for python-docx.
